[project]
name = "bpo-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyqt6>=6.7.1",
    "requests>=2.32.3",
]
